databases:
  - name: opac-db
    databaseName: opac
    user: opac_user
    plan: free

services:
  - type: web
    name: opac-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: opac-db
          property: jdbcConnectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: opac-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: opac-db
          property: password
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: PORT
        value: 8081
      - key: MAIL_USERNAME
        value: sibin9122@gmail.com
      - key: MAIL_PASSWORD
        value: kpmapqxtkztmmeid
    healthCheckPath: /actuator/health
