databases:
  - name: opac-db
    databaseName: opac
    user: opac_user
    plan: free

services:
  - type: web
    name: opac-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        fromDatabase:
          name: opac-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: opac-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: opac-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: opac-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: opac-db
          property: password
      - key: PORT
        value: 8081
      - key: MAIL_USERNAME
        value: sibin9122@gmail.com
      - key: MAIL_PASSWORD
        value: kpmapqxtkztmmeid
    healthCheckPath: /actuator/health
